version: "3.7"
services:
  # Start Postgres
  postgres-db:
    image: postgres
    container_name: postgres-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=task-manager
    ports:
      - "5432:5432"
    networks:
      - postgres-db
  # End Postgres

  # Start Redis
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - redis-network
  # End Redis

networks:
  default: {}
  postgres-db:
    name: postgres
  redis-network:
    driver: bridge